# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-08 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtErfolg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
            ],
            options={
                'verbose_name': 'Erfolgsart',
                'verbose_name_plural': 'Arten von Erfolgen',
            },
        ),
        migrations.CreateModel(
            name='ArtTeilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
            ],
            options={
                'verbose_name': 'Teilnahmeart',
                'verbose_name_plural': 'Arten von Teilnahmen',
            },
        ),
        migrations.CreateModel(
            name='ArtVeranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
                ('teilnahmearten', models.ManyToManyField(blank=True, related_name='veranstaltungsarten', to='Wettbewerbe.ArtTeilnahme')),
            ],
            options={
                'verbose_name': 'Art von Veranstaltungen',
                'verbose_name_plural': 'Arten der Veranstaltungen',
            },
        ),
        migrations.CreateModel(
            name='ArtWettbewerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
                ('erfolgsarten', models.ManyToManyField(blank=True, related_name='wettbewerbsarten', to='Wettbewerbe.ArtErfolg')),
            ],
            options={
                'verbose_name': 'Art von Wettbewerben',
                'verbose_name_plural': 'Arten der Wettbewerbe',
            },
        ),
        migrations.CreateModel(
            name='Erfolg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('nur_name', models.CharField(blank=True, max_length=99)),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Wettbewerbe.ArtErfolg')),
            ],
            options={
                'verbose_name': 'Konkreter Erfolg',
                'verbose_name_plural': 'Konkrete Erfolge',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('nutzer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('nur_name', models.CharField(blank=True, max_length=99)),
                ('ob_weitergekommen', models.BooleanField(default=False)),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Wettbewerbe.ArtTeilnahme')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='Wettbewerbe.Person')),
            ],
            options={
                'verbose_name': 'Konkrete Teilnahme',
                'verbose_name_plural': 'Konkrete Teilnahmen',
            },
        ),
        migrations.CreateModel(
            name='Veranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
                ('beschreibung', models.TextField(blank=True, default='')),
                ('datum_anfang', models.DateField(blank=True, null=True)),
                ('datum_ende', models.DateField(blank=True, null=True)),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Wettbewerbe.ArtVeranstaltung')),
            ],
            options={
                'verbose_name_plural': 'Veranstaltungen',
            },
        ),
        migrations.CreateModel(
            name='Wettbewerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
                ('beschreibung', models.TextField(blank=True, default='')),
                ('datum', models.CharField(blank=True, default='', max_length=255)),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Wettbewerbe.ArtWettbewerb')),
                ('gehoert_zu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abgeleitete_instanzen', to='Wettbewerbe.Wettbewerb')),
                ('veranstaltung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wettbewerbe', to='Wettbewerbe.Veranstaltung')),
            ],
            options={
                'verbose_name_plural': 'Wettbewerbe',
            },
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='Wettbewerbe.Veranstaltung'),
        ),
        migrations.AddField(
            model_name='person',
            name='veranstaltungen',
            field=models.ManyToManyField(related_name='personen', through='Wettbewerbe.Teilnahme', to='Wettbewerbe.Veranstaltung'),
        ),
        migrations.AddField(
            model_name='person',
            name='wettbewerbe',
            field=models.ManyToManyField(related_name='personen', through='Wettbewerbe.Erfolg', to='Wettbewerbe.Wettbewerb'),
        ),
        migrations.AddField(
            model_name='erfolg',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erfolge', to='Wettbewerbe.Person'),
        ),
        migrations.AddField(
            model_name='erfolg',
            name='wettbewerb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erfolge', to='Wettbewerbe.Wettbewerb'),
        ),
        migrations.AlterUniqueTogether(
            name='teilnahme',
            unique_together=set([('person', 'veranstaltung')]),
        ),
        migrations.AlterUniqueTogether(
            name='erfolg',
            unique_together=set([('person', 'wettbewerb')]),
        ),
    ]
