# Generated by Django 2.1 on 2018-12-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wettbewerbkonkret',
            old_name='beschreibung',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='beschreibung',
        ),
    ]
