# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
            ],
            options={
                'verbose_name': 'Art des Tags',
                'verbose_name_plural': 'Arten von Tags',
            },
        ),
        migrations.CreateModel(
            name='WettbewerbKonkret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
                ('beschreibung', models.TextField(blank=True, default='')),
                ('jahrgang', models.PositiveSmallIntegerField()),
                ('datum', models.CharField(blank=True, default='', max_length=255)),
                ('veranstaltung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wettbewerbe', to='Wettbewerbe.Veranstaltung')),
            ],
            options={
                'verbose_name': 'Konkreter Wettbewerb',
                'verbose_name_plural': 'Wettbewerbe Konkret',
            },
        ),
        migrations.CreateModel(
            name='WettbewerbPrinzipiell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('zeit_geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer_geaendert', models.TextField(default='0', editable=False)),
                ('name', models.CharField(max_length=99)),
                ('slug', models.SlugField(blank=True, max_length=99)),
                ('datum', models.CharField(blank=True, default='', max_length=255)),
                ('erfolgsarten', models.ManyToManyField(blank=True, related_name='wettbewerbsarten', to='Wettbewerbe.ArtErfolg')),
                ('fortsetzung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorheriger', to='Wettbewerbe.WettbewerbPrinzipiell')),
            ],
            options={
                'verbose_name': 'Generischer Wettbewerb',
                'verbose_name_plural': 'Wettbewerbe Generisch',
            },
        ),
        migrations.RemoveField(
            model_name='artwettbewerb',
            name='erfolgsarten',
        ),
        migrations.RemoveField(
            model_name='wettbewerb',
            name='art',
        ),
        migrations.RemoveField(
            model_name='wettbewerb',
            name='gehoert_zu',
        ),
        migrations.RemoveField(
            model_name='wettbewerb',
            name='veranstaltung',
        ),
        migrations.AlterField(
            model_name='erfolg',
            name='wettbewerb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erfolge', to='Wettbewerbe.WettbewerbKonkret'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wettbewerbe',
            field=models.ManyToManyField(related_name='personen', through='Wettbewerbe.Erfolg', to='Wettbewerbe.WettbewerbKonkret'),
        ),
        migrations.DeleteModel(
            name='ArtWettbewerb',
        ),
        migrations.DeleteModel(
            name='Wettbewerb',
        ),
        migrations.AddField(
            model_name='wettbewerbkonkret',
            name='wettbewerb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jahrgaenge', to='Wettbewerbe.WettbewerbPrinzipiell'),
        ),
        migrations.AddField(
            model_name='tag',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='Wettbewerbe.ArtTag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='wettbewerbe',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Wettbewerbe.WettbewerbPrinzipiell'),
        ),
    ]
