# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0002_auto_20180224_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='wettbewerbprinzipiell',
            name='slug_prefix',
            field=models.SlugField(default='spam'),
            preserve_default=False,
        ),
    ]
