# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kommentare', '0001_initial'),
        ('Wettbewerbe', '0004_auto_20180227_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='erfolg',
            name='zusatz',
            field=models.CharField(blank=True, default='', max_length=99),
        ),
        migrations.AddField(
            model_name='tag',
            name='kommentarliste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objekt_Tag', to='Kommentare.Liste'),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='kommentarliste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objekt_Veranstaltung', to='Kommentare.Liste'),
        ),
        migrations.AddField(
            model_name='wettbewerbkonkret',
            name='kommentarliste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objekt_WettbewerbKonkret', to='Kommentare.Liste'),
        ),
        migrations.AddField(
            model_name='wettbewerbprinzipiell',
            name='kommentarliste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objekt_WettbewerbPrinzipiell', to='Kommentare.Liste'),
        ),
        migrations.AlterUniqueTogether(
            name='wettbewerbprinzipiell',
            unique_together=set([('slug', 'slug_prefix')]),
        ),
    ]
