# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kommentare', '0002_auto_20180311_1721'),
        ('Wettbewerbe', '0004_auto_20180227_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentarliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objekt', to='Kommentare.Liste')),
                ('tag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kommentarliste', to='Wettbewerbe.Tag')),
                ('veranstaltung', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kommentarliste', to='Wettbewerbe.Veranstaltung')),
                ('wettbewerb', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kommentarliste', to='Wettbewerbe.WettbewerbKonkret')),
            ],
        ),
    ]
