# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0004_auto_20180227_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='erfolg',
            name='zusatz',
            field=models.CharField(blank=True, default='', max_length=99),
        ),
        migrations.AlterUniqueTogether(
            name='wettbewerbprinzipiell',
            unique_together=set([('slug', 'slug_prefix')]),
        ),
    ]
