# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-19 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0005_auto_20180326_1500'),
        ('Wettbewerbe', '0005_auto_20180315_1454'),
    ]

    operations = [
    ]
