# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0005_auto_20180710_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='arttag',
            name='plural',
            field=models.CharField(blank=True, default='', max_length=99),
        ),
    ]
