# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-03 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0005_auto_20180802_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='wettbewerbe',
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='veranstaltungen', to='Wettbewerbe.Tag'),
        ),
        migrations.AddField(
            model_name='wettbewerbprinzipiell',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='wettbewerbe', to='Wettbewerbe.Tag'),
        ),
    ]
