# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-19 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wettbewerbe', '0006_merge_20180519_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='arterfolg',
            name='wichtung',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wettbewerbprinzipiell',
            name='wichtung',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='erfolg',
            name='zusatz',
            field=models.CharField(blank=True, default='', max_length=99),
        ),
    ]
